kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "fluentbit-operator.fullname" . }}
  labels:
    app: {{ template "fluentbit-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.toml: |-
    # This is the config for the fluentbit operator

    [fluentbit-operator]
    rbac = {{ .Values.rbac.enabled }}
    {{- if .Values.tls.enabled }}
    [tls]
    enabled = {{ .Values.tls.enabled }}
    secretName = "{{ .Values.tls.secretName | default (include "fluentbit-operator.fullname" .)  }}"
    sharedKey = "{{ .Values.tls.sharedKey | default (derivePassword 1 "long" (.Release.Time | toString) .Release.Name .Chart.Name ) }}"
    {{- end }}

    [fluent-bit]
    enabled = {{ .Values.fluentbit.enabled }}
    namespace = "{{ default .Release.Namespace .Values.fluentbit.namespace }}"