apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fluentbitoperators.fluentbit.kubesphere.io
  labels:
    app: {{ template "fluentbit-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  group: fluentbit.kubesphere.io
  names:
    kind: FluentBitOperator
    listKind: FluentBitOperatorList
    plural: fluentbitoperators
    singular: fluentbitoperator
  scope: Cluster
  version: v1alpha1