apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fluentbits.logging.kubesphere.io
  labels:
    app: {{ template "fluentbit-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  group: logging.kubesphere.io
  names:
    kind: FluentBit
    listKind: FluentBitList
    plural: fluentbits
    singular: fluentbit
  scope: Namespaced
  version: v1alpha1
