{{- if and .Values.tls.enabled (not .Values.tls.secretName) }}
{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $client := genSignedCert "" nil nil 365 $ca }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fluentbit-operator.fullname" . }}
  labels:
    app: {{ template "fluentbit-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  caCert: {{ b64enc $ca.Cert }}
  clientCert: {{ b64enc $client.Key }}
  clientKey: {{ b64enc $client.Cert }}
{{ end }}