apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: http
  labels:
    http-output-demo: "true"
spec:
  match: "*"
  http:
    host: "log-receiver"
    port: 8080
    format: "json"
#   uri: "/endpoint"
#   headers:
#     key1: value1
#     key2: value2

# -- Basic Auth --

#   httpUser:
#     valueFrom:
#       secretKeyRef:
#         name: log-receiver
#         key: usr
#   httpPassword:
#     valueFrom:
#       secretKeyRef:
#         name: log-receiver
#         key: pass

# ---- TLS ----

#   tls:
#     caFile: "/fluent-bit/secrets/<secret_name>/<key_name>"
#     keyFile: "/fluent-bit/secrets/<secret_name>/<key_name>"
