# permissions to do edit fluentbits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit-editor-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - fluentbits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - fluentbits/status
  verbs:
  - get
  - patch
  - update
