
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - logging.kubesphere.io
  resources:
  - filters
  - fluentbitconfigs
  - fluentbits
  - inputs
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - filters
  - inputs
  - outputs
  verbs:
  - list
- apiGroups:
  - logging.kubesphere.io
  resources:
  - fluentbitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
