apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: dummy
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
spec:
  dummy:
    tag: my_dummy
