apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fluentbit.logging.kubesphere.io
spec:
  group: logging.kubesphere.io
  names:
    kind: FluentBit
    listKind: FluentBitList
    plural: fluentbits
    singular: fluentbit
  scope: Cluster
  version: v1alpha1
