apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluentbit-operator
  template:
    metadata:
      labels:
        name: fluentbit-operator
    spec:
      initContainers:
        - name: setenv
          image: docker:19.03
          command:
            - /bin/sh
            - -c
            - |
              set -ex;
              echo DOCKER_ROOT_DIR=$(docker info -f '{{.DockerRootDir}}') > /fluentbit-operator/env/fluent-bit.env
          volumeMounts:
          - mountPath: /fluentbit-operator/env
            name: env
          - mountPath: /var/run/docker.sock
            name: dockersock
            readOnly: true
      containers:
        - name: fluentbit-operator
          image: dockerhub.qingcloud.com/kslogging/fluentbit-operator:latest
          command:
          - fluentbit-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - mountPath: /fluentbit-operator/config
            name: config
          - mountPath: /fluentbit-operator/env
            name: env
      volumes:
      - configMap:
          name: fluentbit-operator-config
        name: config
      - emptyDir: {}
        name: env
      - hostPath:
          path: /var/run/docker.sock
        name: dockersock
