apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluentbit-operator
  template:
    metadata:
      labels:
        name: fluentbit-operator
    spec:
      containers:
        - name: fluentbit-operator
          image: dockerhub.qingcloud.com/kslogging/fluentbit-operator:latest
          command:
          - fluentbit-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - mountPath: /fluentbit-operator/config
            name: config
      volumes:
      - configMap:
          name: fluentbit-operator-config
        name: config
