apiVersion: logging.kubesphere.io/v1alpha1
kind: FluentBit
metadata:
  name: fluentbit-sample
  labels:
    app: fluent-bit
spec:
  image: kubespheredev/fluent-bit:v1.3.7
  imagePullPolicy: IfNotPresent
  positionDB:
    emptyDir: {}
  fluentBitConfigName: fluentbitconfig-sample
